import * as fs from 'fs';
import { listLocalBallistics } from '../browseBallistics';
import { writeFsText } from '../assetIo';
import { CLASS_PREFIX, classMapFsPath, ensureDir, generatedClassFsPath, generatedDirFs } from '../paths';

export function regenerateClassMap(): { ok: boolean; count: number; path: string } {
  ensureDir(generatedDirFs());
  const items = listLocalBallistics().filter(
    (s) => s.exportFlag && fs.existsSync(generatedClassFsPath(s.ballisticId))
  );

  const imports: string[] = [];
  const entries: string[] = [];

  for (const s of items) {
    const cls = `${CLASS_PREFIX}${s.ballisticId}`;
    imports.push(`import { ${cls} } from './${cls}';`);
    entries.push(`  ${s.ballisticId}: () => new ${cls}(),`);
  }

  const code = `/*
 * AUTO-GENERATED by ballistic-editor. Do not edit manually.
 */
import type { AbsLinearBallistic } from '../AbsLinearBallistic';
${imports.join('\n')}

export type TsBallisticFactory = () => AbsLinearBallistic;

export const TsBallisticClassMap: Record<number, TsBallisticFactory> = {
${entries.join('\n')}
};

export function createTsBallistic(ballisticId: number): AbsLinearBallistic | null {
  const factory = TsBallisticClassMap[ballisticId];
  return factory ? factory() : null;
}
`;

  const out = classMapFsPath();
  writeFsText(out, code);
  return { ok: true, count: items.length, path: out };
}
