import * as fs from 'fs';
import { listLocalModifiers } from '../browseModifiers';
import { writeFsText } from '../assetIo';
import { CLASS_PREFIX, classMapFsPath, ensureDir, generatedClassFsPath, generatedDirFs } from '../paths';

export function regenerateClassMap(): { ok: boolean; count: number; path: string } {
  ensureDir(generatedDirFs());
  const items = listLocalModifiers().filter(
    (s) => s.exportFlag && fs.existsSync(generatedClassFsPath(s.modifierId))
  );

  const imports: string[] = [];
  const entries: string[] = [];

  for (const s of items) {
    const cls = `${CLASS_PREFIX}${s.modifierId}`;
    imports.push(`import { ${cls} } from './${cls}';`);
    entries.push(`  ${s.modifierId}: () => new ${cls}(),`);
  }

  const code = `/*
 * AUTO-GENERATED by modifier-editor. Do not edit manually.
 */
import type { AbsModifier } from '../AbsModifier';
${imports.join('\n')}

const MAP: Record<number, () => AbsModifier> = {
${entries.join('\n')}
};

export function createTsModifier(templateId: number): AbsModifier | null {
  const factory = MAP[templateId | 0];
  return factory ? factory() : null;
}

export function listExportedModifierIds(): number[] {
  return Object.keys(MAP).map((k) => Number(k));
}
`;

  const out = classMapFsPath();
  writeFsText(out, code);
  return { ok: true, count: items.length, path: out };
}
