import * as fs from 'fs';
import { listLocalSkills } from '../browseSkills';
import { writeFsText } from '../assetIo';
import { CLASS_PREFIX, classMapFsPath, ensureDir, generatedClassFsPath, generatedDirFs } from '../paths';

export function regenerateClassMap(): { ok: boolean; count: number; path: string } {
  ensureDir(generatedDirFs());
  const skills = listLocalSkills().filter((s) => s.exportFlag && fs.existsSync(generatedClassFsPath(s.skillId)));

  const imports: string[] = [];
  const entries: string[] = [];

  for (const s of skills) {
    const cls = `${CLASS_PREFIX}${s.skillId}`;
    imports.push(`import { ${cls} } from './${cls}';`);
    entries.push(`  ${s.skillId}: () => new ${cls}(),`);
  }

  const code = `/*
 * AUTO-GENERATED by skill-editor. Do not edit manually.
 */
import type { AbsAbility } from '../graph/AbsAbility';
${imports.join('\n')}

export type TsAbilityFactory = () => AbsAbility;

export const TsAbilityClassMap: Record<number, TsAbilityFactory> = {
${entries.join('\n')}
};

export function createTsAbility(skillId: number): AbsAbility | null {
  const factory = TsAbilityClassMap[skillId];
  return factory ? factory() : null;
}
`;

  const out = classMapFsPath();
  writeFsText(out, code);
  return { ok: true, count: skills.length, path: out };
}
