/*
 * AUTO-GENERATED by modifier-editor from modifier graph {{MODIFIER_ID}}.
 * Do not edit manually — re-export from the Buff editor.
 */
import { Node, Vec3 } from 'cc';
import { AbsModifier } from '../AbsModifier';

export class {{CLASS_NAME}} extends AbsModifier {
    public readonly modifierTemplateId = {{MODIFIER_ID}};
{{FIELDS}}
{{LIFECYCLE_METHODS}}
{{BLUEPRINT_METHODS}}
}
