/*
 * AUTO-GENERATED by skill-editor from skill graph {{ABILITY_ID}}.
 * Do not edit manually — re-export from the skill editor.
 */
import { Node, Vec3 } from 'cc';
import { AbsAbility } from '../graph/AbsAbility';

export class {{CLASS_NAME}} extends AbsAbility {
    public readonly abilityId = {{ABILITY_ID}};
{{FIELDS}}
{{LIFECYCLE_METHODS}}
{{BLUEPRINT_METHODS}}
}
