/*
 * AUTO-GENERATED by ballistic-editor from ballistic graph {{BALLISTIC_ID}}.
 * Do not edit manually — re-export from the ballistic editor.
 */
import { Node, Vec3 } from 'cc';
import { AbsLinearBallistic } from '../AbsLinearBallistic';

export class {{CLASS_NAME}} extends AbsLinearBallistic {
    public readonly ballisticTemplateId = {{BALLISTIC_ID}};
{{FIELDS}}
{{LIFECYCLE_METHODS}}
{{BLUEPRINT_METHODS}}
}
